### PR TITLE
Show how the button is too far on the left when there is code right b…

### PR DESCRIPTION
**Pull request by maelle**
…elow the header :-s

### CODE REVIEW

**Comment by maelle** [comment]
@hadley https://605dfaa8618c2d5dcb88c344--pkgdown-dev.netlify.app/articles/pkgdown.html The first code chunk is not as wide as the whole content because there's the logo, but the copy-paste button still appears on the right. :grimacing:

**Comment by maelle** [comment]
A fix could be adding a rule like

```css
.page-header.pb-2.mt-4.mb-2.border-bottom.toc-ignore {
  margin-bottom: 30px !important;
}
```

image

**Comment by hadley** [comment]
We could also just move `library("pkgdown")` to the end of the intro, which is where it normally lives. I think it's pretty unusual to start a vignette with code.

**Comment by maelle** [comment]
Good then it's not something to fix.

**Pull request closed without merging**
