### PR TITLE
Fix \special HTML rendering

### PR DESCRIPTION
**Pull request by klmr**
When implementing #1345 I didn’t account for the fact that `\special` tags can have more than one child node (e.g. `\special{foo(\dots)}`). This PR fixes that.

The added test case usage is taken verbatim from base R ([`src/library/base/man/Paren.Rd`](https://github.com/wch/r-source/blob/ce2907e7f01427da3649ebe137a981b8587a5211/src/library/base/man/Paren.Rd#L12)) so it represents real usage.

### CODE REVIEW

**Comment by klmr** [comment]
… no idea why the tests fail for R ≤3.6. 😦

**Comment by klmr** [comment]
Ah, apparently it’s due to a [bug in R](https://bugs.r-project.org/show_bug.cgi?id=17727) that was only fixed in 4.0.0.

What’s the best way of handling this in the test? `skip_if(R.version$major < '4')` with a comment referring the bug report?

**Comment by hadley** [comment]
Yeah, except I'd express that as `skip_if_not(getRversion() >= "4.0.0")`

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
