### PR TITLE
WIP - Fix travis deploy

### LINKED ISSUE #1274: pkgdown::deploy_site_github reports git error on Travis-CI
Hi,

I have a peculiar error, which is currently affecting my travis config.

This is the deploy config I am using
```
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY",""))'
  skip_cleanup: true
```

and this results in a git error "remote: Invalid username or password." for all repos I have tried so far. The error appeared yesterday for the first time. 

I tried to debug this on the Travis-CI system, but everthing seems to be in order. The ssh key get written correctly, but somehow this error appears during the last step, the `git push`. Running `pkgdown::deploy_site_github` locally works.

Do anyone can offer some advice how to debug this further? I already reset my travis deploy keys, no luck so far.

Felix

Link to the Travis-CI build: https://travis-ci.com/github/FelixErnst/Modstrings/builds/154396023

### LINKED ISSUE #1275: pkgdown::deploy_site_github() fails at git push, does not seem to use SSH
This appeared with pkgdown v1.5, both CRAN and dev.

Log - relevant part:
 
```
── Extra files for GitHub pages ────────────────────────────────────────────────

── Commiting updated site ──────────────────────────────────────────────────────

Running git add -A .

Running git commit --allow-empty -m \

  'Built site for reschola: 0.2.7.9000@e5fbe49'

[gh-pages 738c770] Built site for reschola: 0.2.7.9000@e5fbe49

 43 files changed, 824 insertions(+), 727 deletions(-)

── Deploying to GitHub Pages ───────────────────────────────────────────────────

Running git remote -v

origin	https://github.com/scholaempirica/reschola.git (fetch)

origin	https://github.com/scholaempirica/reschola.git (push)

Running git push --force origin 'HEAD:gh-pages'

remote: Invalid username or password.

fatal: Authentication failed for 'https://github.com/scholaempirica/reschola.git/'

Error: System command 'git' failed, exit status: 128, stdout & stderr were printed

 Stack trace:

 1. pkgdown::deploy_site_github()

 2. pkgdown:::deploy_to_branch(pkg, commit_message = commit_message,  ...

 3. pkgdown:::github_push(dest_dir, commit_message, remote, branch)

 4. pkgdown:::with_dir(dir, { ...

 5. base:::force(code)

 6. pkgdown:::git("push", "--force", remote, paste0("HEAD:", branch))

 7. processx::run("git", c(...), echo_cmd = echo_cmd, echo = echo,  ...

 8. throw(new_process_error(res, call = sys.call(), echo = echo,  ...

 x System command 'git' failed, exit status: 128, stdout & stderr were printed 

── Removing worktree ───────────────────────────────────────────────────────────

Running git worktree remove /tmp/RtmpC2bjSY/file3a426e51abcd

Execution halted

Script failed with status 1

failed to deploy
```
Travis config:

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

```

Deploying the same code works with pkgdown v1.4.1, i.e. when `before_cache: Rscript -e 'remotes::install_cran("pkgdown")'` is replaced with `before_cache: Rscript -e 'remotes::install_version("pkgdown", version = "1.4.1")'`.

From the log it seems that pkgdown is using HTTPS for pushing to github, which does not seem right given that it should rely on the RSA deploy key.

All builds and logs: https://travis-ci.org/github/scholaempirica/reschola

### PR DESCRIPTION
**Pull request by jimhester**
Fixes #1274 
Fixes #1275

### CODE REVIEW

**Comment by FelixErnst** [comment]
4dab6a9 fixes #1274 and #1275

https://travis-ci.com/github/FelixErnst/Structstrings/builds/155654019

**Comment by jimhester** [comment]
Actually c5ae5e3 is what was run in that build. You can tell because it runs `git remote set-url` e.g. https://travis-ci.com/github/FelixErnst/Structstrings/builds/155654019#L5143-L5144

I realize that commit did not exist in this PR until you had re-started the build, but it took a while to get to the deploy step and by the time it had this PR was updated.

**Comment by jayhesselberth** [comment]
Can you add a news bullet?

**Comment by jimhester** [comment]
added news

**Comment by jayhesselberth** [comment]
Thanks!

**Pull request merged**
