### PR TITLE
add CRAN release dates to news items

### LINKED ISSUE #444: Add release dates to news

### PR DESCRIPTION
**Pull request by jayhesselberth**
Preview at https://priceless-hawking-87152b.netlify.com/news/index.html

- closes #444

### CODE REVIEW

**Comment by jayhesselberth** [comment]
Preview https://unruffled-einstein-cd4819.netlify.com/

**Comment by hadley** [comment]
Perfect! I'll merge once I've completed #531

**Comment by hadley** [comment]
Would you mind merge/rebasing?

**Comment by hadley** [comment]
Btw I'm trying to not take any more dependencies, so I'll rewrite to eliminate the use of dplyr and tidyr.

**Comment by hadley** [comment]
Sorry, I should have lead with: Thanks for all your hard work on this pull requests (and others!). It's much appreciated 😃

**Pull request merged**
