### PR TITLE
Wrapping downlit output in pre() lost the dependencies attribute.

### PR DESCRIPTION
**Pull request by dmurdoch**
Fixes issue #1689 .

### CODE REVIEW

**Comment by dmurdoch** [comment]
This also fixes #1720 now.

**Comment by hadley** [comment]
Still coming back up to speed on this, but do you think it makes sense to add a `replay_html.shiny.tag()` method to downlit? 

```R
registerS3method("replay_html", "shiny.tag", envir = asNamespace("downlit"),
  function(x, ...) {
    structure(as.character(x), dependencies = htmltools::htmlDependencies(x))  
  }
)
```

Then the code to check that `highlight_examples()` preserves dependencies becomes something like this:

```R
dummy_dep <- htmltools::htmlDependency("dummy", "1.0.0", "dummy.js")
pkgdown_print.foo <- function(x, visible) {
  htmltools::attachDependencies(htmltools::div("test"), dummy_dep)
}

local_context_eval(list())
highlight_examples("structure(list(), class = 'foo')")
```

**Comment by hadley** [comment]
Oooh, that's what https://github.com/ramnathv/htmlwidgets/pull/404/files does — maybe it's simpler to put the `replay_html.htmlwidget` and `pkgdown_print.htmlwidget` methods in downlit and pkgdown respectively? Then that PR would only be needed to improve the default sizing.

**Comment by hadley** [comment]
`replay_html.htmlwidget()` calls `htmltools:::tagify()` which calls `htmltools::as.tags()` which calls `htmlwidgets::as.tags.htmlwidget()` which calls `htmlwidgets::toHTML()`.  That calls `resolveSizing()` which, because `standalone = FALSE` (the default), it runs:

```R
    return(list(
      width = x$width %||% prop(sp, "defaultWidth") %||% DEFAULT_WIDTH,
      height = x$height %||% prop(sp, "defaultHeight") %||% DEFAULT_HEIGHT
    ))
```

That suggests maybe we could just modify `x$width` and `x$height` (if null) to `with(settings, fig.width*dpi)`. And thus eliminate the need for the htmltools PR altogether? If that seems feasible, I'm happy to make the changes to downlit and pkgdown.

(I can certainly push the htmltools PR + release through with a bit of effort, but I think it would make things simpler if all the changes lived in pkgdown + downlit).

**Comment by dmurdoch** [comment]
I've been driving all day, so it'll take me a bit of time to digest these new messages.  Be back soon...

**Comment by dmurdoch** [comment]
Yes, I think it would be fine to put the htmlwidget methods in `pkgdown` and `downlit` instead of `htmlwidgets`.  

This PR 1719 had two other contributions in it, and I'm not sure where to look to see if those have been addressed.  The first was to fix an accidental loss of the `dependencies` attribute, and the second was to add a test to make sure it doesn't happen again.  Will keep looking...

**Comment by hadley** [comment]
PRs are at https://github.com/r-lib/pkgdown/pull/1780 and https://github.com/r-lib/downlit/pull/110

**Pull request closed without merging**
