### PR TITLE
Don't preview by default

### PR DESCRIPTION
**Pull request by hadley**
@olivroy @jayhesselberth @maelle What do y'all think of this? I've started finding the automatic preview annoying since it brings the browser to the front, and there's already a link for me to click if I want to see the page.

### CODE REVIEW

**Comment by olivroy** [comment]
I am also okay with this. Although when it takes long, I really appreciate that popup (serves as a notification). So maybe, change the default for everything except `build_site()`?

**Comment by jayhesselberth** [comment]
Agree, changing the default on everything except `build_site()` seems a good compromise.

**Comment by maelle** [comment]
I agree and like the option idea.

**Comment by hadley** [comment]
I agree that the default should be true for `build_site()`. I think an option is probably a bit more work than is warranted here, given the array of ways we already have for folks to preview the site.

**Pull request merged**
