### PR TITLE
Adding some missing French translations

### PR DESCRIPTION
**Pull request by jplecavalier**
Note: I used the terminology "article" instead of "vignette" for the index page (line 30) since I find it is more accurate.

### CODE REVIEW

**Review by maelle — APPROVED** [review]
Merci !

**Comment by hadley** [comment]
@jplecavalier can you please mark the PR as editable by develoeprs?

**Comment by jplecavalier** [comment]
Sorry for the delay, I was away for the last couple of days. @Hadley I thought I was good with the "Allow edits by maintainers" option checked, is there something else I'm missing?

**Comment by hadley** [comment]
@jplecavalier hmmmm, it wasn't working when I last tried but seems fine now 😄

**Pull request merged**
