### PR TITLE
Add Portuguese translation

### PR DESCRIPTION
**Pull request by rich-iannone**
This adds a Portuguese `.po` file (authored with Poedit).

### CODE REVIEW

**Comment by dieghernan** [comment]
You may be interested in #1906 , it would add new keys to be translated

**Comment by hadley** [comment]
@rich-iannone what else does this need?

**Comment by rich-iannone** [comment]
@Hadley The translations in the .po file are good so nothing else to do there. However, the provided .mo file was created from Poetedit, which is probably not what you want. Is the preference to use `potools::po_compile()`?

**Comment by hadley** [comment]
If it's good from your end, I'll take it from here.

**Comment by rich-iannone** [comment]
Added one last fix. The .mo file really needs to be updated now (will entrust that to you).

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
