### PR TITLE
Pandoc + callr updates

### PR DESCRIPTION
**Pull request by maelle**
Locally I am seeing

image

```
testthat::snapshot_review('rmarkdown')
```

### CODE REVIEW

**Comment by maelle** [comment]
"pandoc fail" is such an appropriate name :joy_cat:

**Comment by maelle** [comment]
Maybe the skipping in 

https://github.com/r-lib/pkgdown/blob/0183403320bf81d68a14ab062e746de87fe24ebc/tests/testthat/test-rmarkdown.R#L17

should be tweaked

**Comment by hadley** [comment]
I still see this problem even when I revert to pandoc 2.17.1 (with `pandoc::pandoc_activate("2.17.1")`) so I wonder if something else is at play.

**Comment by hadley** [comment]
I'm exploring if this is a callr/processx issue with Gabor.

**Comment by maelle** [comment]
I'll wait for the release, then.

**Pull request merged**
