### PR TITLE
Implement sticky navbar in css

### PR DESCRIPTION
**Pull request by Bisaloo**
See https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects

Not entirely sure I did everything right so feel free to test more before merging (I will do the same on my end).

### CODE REVIEW

**Comment by jayhesselberth** [comment]
This works for me on Chrome. Can you check a few other browsers?

**Comment by Bisaloo** [comment]
I worked with Firefox. I can tests on other browsers tomorrow. Feel free to ping me again if I forget again and nothing happens in the next couple of days.

Note to self: looks like the `webkit-` prefix is still necessary for most safari versions: https://caniuse.com/#feat=css-sticky

**Comment by Bisaloo** [comment]
Tested on Firefox, Chromium and midori (based on an old webkit version). It looks fine.

**Comment by Bisaloo** [comment]
Tested on latest safari version as well (12.1) and it works fine with the `-webkit-` prefix.

**Comment by jayhesselberth** [comment]
In general I am in favor of relying less on external libraries for the site. Looks fine to me.

**Pull request merged**
