### PR TITLE
Provide option to disable internet connections

### LINKED ISSUE #762: not check remote url for pure GitHub package
pkgdwon check remote urls like https://cloud.r-project.org, which makes it convenient to automatically create appropriate urls. But that also brings trouble for pure GitHub package. Although `httr::http_error()` makes it compatible with pure GitHub package, Chinese developers have to access _every_ foreign website with cautions. 

Here is the error message I get with my [rGEO](https://github.com/dongzhuoer/rGEO) package

```
── Building news ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds
Calls: withCallingHandlers ... request_fetch.write_memory -> <Anonymous> -> .handleSimpleError -> h
Execution halted
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds
```

I modified pkgdown's source code, comment out code which access remote url (`repo_link` & `pkg_timeline`), then everything works fine. (Maybe it's a general problem for pure GitHub package, not restricted to Chinese developers.)

### LINKED ISSUE #766: Error in build_site(): curl::curl_fetch_memory(url, handle = handle) "Couldn't connect to server"
I am trying to use `build_site()` behind a firewall and it fails (fresh install package install: version 1.1.0, R 3.3.2). I can 

```r
# traceback
1: build_home()
...
19: curl::curl_fetch_memory(url, handle = handle)
```

using `dump.frames()` and `debugger()` I think the problem is that the function tries to access `"https://cloud.r-project.otg/package=mypackage"` which it cannot do because there is no internet access. 

- Is there a way to turn this off?
- Why is the function not using the repo specified in in options (`options("repos")` does point to a working internal CRAN mirror) ... I just saw that the url does not simply looks into the CRAN mirror structure but does an API-call - so it will not work with the internal mirror anyways, I think. 

*Sorry for the sparse background info - no sessionInfo()-output and so forth - I have no option to copy paste output*

### LINKED ISSUE #773: Option to disable internet connections
pkgdown connects to CRAN during the build process to check for:

- the package's existence there (https://github.com/r-lib/pkgdown/blob/master/R/build-home-index.R#L76)
- the package's release timeline (https://github.com/r-lib/pkgdown/blob/master/R/build-news.R#L161).

This causes build errors for users with limited internet connectivity (#762, #766).

Using `nslookup` is not ideal because even real connections might fail intermittently (#767).

We need a way to let users explicitly disable internet connections. This could be:

- A param (`internet = FALSE`) that is propagated through the build process.
- An user-defined option (#768) (e.g., `getOption(pkgdown.internet)`)

This flag would be checked by `build_news()` and `build_home_index()` before connecting to  CRAN.

### PR DESCRIPTION
**Pull request by jayhesselberth**
Closes #773. Closes #762. Closes #766.

### CODE REVIEW

**Comment by dongzhuoer** [comment]
Thank you very much for the code, but I'm afraid that there is still one step to get it work.

I set `options(pkgdown.internet = F)` in my `~/.Rprofile`, then 

```r
> pkgdown::build_home()
── Building home ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Reading 'news.md'
Writing 'index.html'
── Previewing site ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> pkgdown::build_site()
══ Building pkgdown site ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Reading from: '/media/computer/work/R/hgnc'
Writing to:   '/media/computer/work/R/hgnc/docs'
── Initialising site ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Writing 'sitemap.xml'
● Edit '_pkgdown.yml'
── Building home ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Reading 'news.md'
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: cloud.r-project.org
Calls: withCallingHandlers ... request_fetch.write_memory -> <Anonymous> -> .handleSimpleError -> h
Execution halted
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: cloud.r-project.org
```

**Comment by dongzhuoer** [comment]
I found that `build_site()` use `new_process = TRUE` by default. In this scenario, I think it's quite intuitive to enable `.Rprofile` in the new process or at least add option to let the user explicitly specify it. Otherwise, user have to run `pkgdown::build_site(new_process = F)` (I don't think it's a good idea to have to run pkgdown in a dirty process in order to get `pkgdown.internet` working)

**Comment by jayhesselberth** [comment]
I think we need to add `user_profile = TRUE` to the [`callr::r()` call](https://github.com/r-lib/pkgdown/blob/bee7f26b1755a3d50170c852ebaf395862aeab8c/R/build.r#L316).

But then you have to set the option via `.Rprofile`.

**Comment by dongzhuoer** [comment]
Yeah, I think it's the natural way.

**Comment by hadley** [comment]
I think it would be better to set the option explicitly in the new process

**Comment by dongzhuoer** [comment]
How can you achieve that? `build_site(process_setup = function() {options(pkgdown.internet = F)})`? I think the syntax is ugly.

Instead `.Rprofile` is the natural way to run set up code before a R process begins. we can use `build_site(use_Rprofile = TRUE)`. 

The only drawback is when user want to run some code `build_site(new_process = F)`, but not `build_site(new_process = F)`. However, in normal case, I think this need is rare.

**Comment by hadley** [comment]
pkgdown would do it for you. 

Writing to `.Rprofile` is not a good solution.

**Comment by petermeissner** [comment]
:+1:  For me the builds now run through with:

```
options(pkgdonw.internet = FALSE)
pkgdown::buil_site(new_process = FALSE)
```


:zap: **But there are more problems ahead.** Since internet is no option looking at the docs in a browser will result in several files the browser cannot obtain:

- jquery-3.1.0.min.js
- bootstrap.min.css
- bootstrap.min.js
- font-awesome.min.css
- clipboard.min.js
- sticky-kit.js
- Math.Jax.js?config=Tex-AMS-MML_HTMLorMML

**Comment by dongzhuoer** [comment]
@petermeissner I know this way, the down point is that we have to run pkgdown in a dirty session.

**Comment by dongzhuoer** [comment]
I think we might have gone so far. 

What I'm talking about originally is to disable internet when build the documentation, not when view the documentation. 

Maybe we need separate option for these two senarios.

**Comment by BruceZhaoR** [comment]
@jayhesselberth  https://github.com/r-lib/pkgdown/commit/56f3a657ed73fd769331002a5cd894307affda39#r30192460

`https://cran.r-project.org/package=` may be better than `https://cloud.r-project.org/package=` ?

**Pull request merged**
