### PR TITLE
fix doc for build_home() and pkgdown/index.md

### PR DESCRIPTION
**Pull request by cderv**
`pkgdown/index.md` is recognized and not `_pkgdown/index.md`

https://github.com/r-lib/pkgdown/blob/d34ce5fc8317e409437c502e8af3c2bca2b894c3/R/build-home-index.R#L4-L9

cc @apreshill

### CODE REVIEW

**Comment by cderv** [comment]
maybe I should not have run the pr command as it seems other changes went in...

**Comment by hadley** [comment]
That's our fault, not yours.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
