### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by sharlagelfand**
:~)

### CODE REVIEW

**Comment by jayhesselberth** [comment]
Please `roxygenize()` and commit the Rd file.

**Comment by sharlagelfand** [comment]
ugh of course, sorry! did it quickly on github

**Comment by jayhesselberth** [comment]
Thanks!

**Comment by hadley** [comment]
@jayhesselberth btw you can type `/document` in a comment, and a GitHub action should automatically re-`document()` and check in the results

**Pull request merged**
