### PR TITLE
Paragraph flattening respects preserved html

### LINKED ISSUE #1208: Paragraph flattening adds excess paragraph tags
I've been struggling with this problem, which for the longest time I assumed was buried in rmarkdown or pandoc. 

The `flatten_para()` pkgdown helper is adding excess paragraph tags, which can produce unwanted html markup in the generated reference pages.

This is the output you would see using a `buttonGroupInput()` in a shiny app. 

image

This is what I see on the pkgdown generated page.

image

Here is the markup from the generated page.

```html
<div id="flavors" class="yonder-button-group btn-group btn-group-info d-flex" role="group">
<button type="button" class="btn" value="mint"><p></p>
<p>Mint
</p></button>
<button type="button" class="btn" value="strawberry"><p></p>
<p>Strawberry
</p></button>

. . .
```

The markup `<button type="button" class="btn" value="mint">Mint/button>` is converted into 
`<button type="button" class="btn" value="mint"><p></p><p>Mint</p></button>`.

I will see about adjusting the rules of `flatten_para()` to better account for this case. An "easy" check might be to ignore text inside `<!--html_preserve-->`. I'm not certain this is actually easy because it may not be simple to check the context of a potential paragraph location.

### PR DESCRIPTION
**Pull request by nteetor**
This modifies `flatten_para()` so it no longer modifies html inside `<!--html_preserve-->. . .<!--/html_preserve-->`. This would fix #1208. There are still a couple of todos for me if this change would be accepted.

- [x] reprex
- [ ] add tests to `test-rd-html.R`
- [ ] update news

### CODE REVIEW

**Comment by hadley** [comment]
I don’t remember this code that well, but this approach doesn’t seem quite right to me — why is flatten_para() touching any returned HTML in the first place?

**Comment by nteetor** [comment]
The HTML that `flatten_para()` is processing in this case is found in the source rd files. I'm using `@includeRmd` and some the included code chunks return asis html. During the rd to html conversion that included html is part of the text processed by `flatten_para()`.

**Comment by hadley** [comment]
Can you please provide a minimal reprex?

**Comment by nteetor** [comment]
Will do. I have most of a reprex put together. I'm working on the final step the proper sequence of rd parsing function calls from pkgdown.

**Comment by nteetor** [comment]
### Summary

The reprex wasn't so simple in the end. Please let me know what needs clarifying. 

There is a problem with paragraph tags. However, the problem is different than I first thought. It looks like `<p>` and `</p>` tags are getting interleaved with other html tags. Browsers attempt to correct the stray tags and the result is not just some extra, but many extra paragraph tags. My branch does fix the problem, see the final section. But, there may be a way to adjust only the existing rules at https://github.com/r-lib/pkgdown/blob/master/R/rd-html.R#L13-L52 and still resolve the problem. I won't make any changes though until you've had a chance to review. 

### Reprex with r-lib/pkgdown installed

```` r
# remotes::install_github('r-lib/pkgdown')
library(pkgdown)
library(roxygen2)
library(htmltools) # needed in temp rmd file

rmd_tmp <- tempfile(fileext = ".Rmd")
cat(
  file = rmd_tmp,
  sep = "\n",
  "```{r results='asis'}",
  "library(htmltools)",
  "tags$button(",
  "  'Cras justo odio'",
  ")",
  "```"
)

rox_tmp <- tempfile(fileext = ".R")
cat(
  file = rox_tmp,
  sep = "\n",
  "#' @title Title",
  paste("#' @includeRmd", rmd_tmp),
  "#' @name test",
  "NULL"
)

rox_str <- paste(readLines(rox_tmp), collapse = "\n")

# NOTE: if printed, this text _will not_ show the relevant <!-html_preserve->
# comments, it looks like html comments are dropped during the reprex
# rendering (the comment here is intentionally malformed or reprex() throws an
# error)
rox_out <- roc_proc_text(rd_roclet(), rox_str)[[1]]
rox_fmt <- rox_out$format()
rox_details <- rox_out$get_section("details")$value

# Generate the rd structure parsed by pkgdown
rd_details <- pkgdown:::rd_text(rox_details, fragment = TRUE)

# This is where I struggled, both `pkgdown:::as_data()` and
# `pkgdown::rd2html()` eventually call `pkgdown:::flatten_para()`, but I
# couldn't seem to produce an object both functions would accept (most often
# `as_data()` would not have an applicable method)

# As a compromise I am directly passing the rd details section to
# `flatten_para()`.
rd_para <- pkgdown:::flatten_para(rd_details)

cat(rd_para)
#> <p><div class="r"></p><pre>library(htmltools)
#> tags$button(
#>   'Cras justo odio'
#> )
#> </pre><p></div>
#> <!--html_preserve-->
#> 
#> 
#> <button></p>
#> 
#> <p>Cras justo odio
#> </button>
#> 
#> 
#> <!--/html_preserve--></p>
````

<sup>Created on 2020-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### Same reprex, but with nteetor/pkgdown@master-nt-preserve-html installed

<details>
  <summary>Same reprex code as above</summary>

```` r
# remotes::install_github('nteetor/pkgdown@master-nt-preserve-html')
library(pkgdown)
library(roxygen2)
library(htmltools) # needed in temp rmd file

rmd_tmp <- tempfile(fileext = ".Rmd")
cat(
  file = rmd_tmp,
  sep = "\n",
  "```{r results='asis'}",
  "library(htmltools)",
  "tags$button(",
  "  'Cras justo odio'",
  ")",
  "```"
)

rox_tmp <- tempfile(fileext = ".R")
cat(
  file = rox_tmp,
  sep = "\n",
  "#' @title Title",
  paste("#' @includeRmd", rmd_tmp),
  "#' @name test",
  "NULL"
)

rox_str <- paste(readLines(rox_tmp), collapse = "\n")

# NOTE: if printed, this text _will not_ show the relevant <!-html_preserve->
# comments, it looks like html comments are dropped during the reprex
# rendering (the comment here is intentionally malformed or reprex() throws an
# error)
rox_out <- roc_proc_text(rd_roclet(), rox_str)[[1]]
rox_fmt <- rox_out$format()
rox_details <- rox_out$get_section("details")$value

# Generate the rd structure parsed by pkgdown
rd_details <- pkgdown:::rd_text(rox_details, fragment = TRUE)

# This is where I struggled, both `pkgdown:::as_data()` and
# `pkgdown::rd2html()` eventually call `pkgdown:::flatten_para()`, but I
# couldn't seem to produce an object both functions would accept (most often
# `as_data()` would not have an applicable method)

# As a compromise I am directly passing the rd details section to
# `flatten_para()`.
rd_para <- pkgdown:::flatten_para(rd_details)
````

</details>

Notice, the button no longer includes `<p>` or `</p>` tags.

````r
cat(rd_para)
#> <p><div class="r"></p><pre>library(htmltools)
#> tags$button(
#>   'Cras justo odio'
#> )
#> </pre></div>
#> <!--html_preserve-->
#> 
#> 
#> <button>
#> 
#> 
#> 
#> Cras justo odio
#> </button>
#> 
#> 
#> <!--/html_preserve-->
````

<sup>Created on 2020-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nteetor** [comment]
Here is a live example of extra `<p>` elements getting inserted into a page.

https://nteetor.github.io/cascadess/reference/background.html#buttons

**Comment by hadley** [comment]
Closing this because I want to get a better understanding the of problem first.

**Pull request closed without merging**
