### PR TITLE
add search capability to pkgdown

### LINKED ISSUE #396: search
It would be great to search a pkgdown site.

### PR DESCRIPTION
**Pull request by jayhesselberth**
- closes #396

There is a functional implementation at https://jayhesselberth.github.io/pkgdown-search/

Can you take a look @jennybc and see what you think?

Note that search capability doesn't work until the site is served from github because jQuery doesn't support JSON loading via local cross origin requests.

### CODE REVIEW

**Comment by jennybc** [comment]
Exciting development! I don't play a reviewer role for pkgdown, esp. not for a substantial component like this. So will leave it for @hadley to handle.

**Comment by jayhesselberth** [comment]
Couple of comments:

1. Currently the very first search sent to search.html fails because the index isn't built yet. Needs a fix on the JS side.

2. Display of the results can be improved by also noting their type. Instead of: 

<ul>
<li>pkgdown</li>
<li>build_site</li>
</ul>

Links could be:

<ul>
<li>pkgdown (vignette)</li>
<li>build_site (Rd)</li>
</ul>

3. The README content should be indexed for searching. 

4. A more sophisticated improvement is to included a portion of the returned result with the search word highlighted.

**Comment by hadley** [comment]
Oooh, nice!

How hard would it be to make the UI more like https://tensorflow.rstudio.com/? i.e. type-ahead search then results displayed in a modal dialog?

**Comment by jayhesselberth** [comment]
I dig some quick digging but can't tell what the search facility is on the tensorflow website. All the pkgdown docs in the github repo are redirects to somewhere else. Also that site is built using Hugo.

**Comment by jayhesselberth** [comment]
The search capability on  https://tensorflow.rstudio.com/ is from swiftype, a commercial solution (https://swiftype.com/)

**Comment by pat-s** [comment]
@jayhesselberth While the search function you implemented works on your [site](https://rnabioco.github.io/valr/), it does not work on [mine](https://pat-s.github.io/mlr/index.html). Did you change anything additional locally compared to this PR implementation?

**Comment by jayhesselberth** [comment]
It works on your site, but there's currently an issue that prevents results from displaying the first time a search is entered. Go to the site, search for "learning" and it should go to an empty search page. Search for learning again, and the results should appear.

I think this is a javascript issue but haven't tracked it down yet.

**Comment by jayhesselberth** [comment]
[Mkdocs](http://www.mkdocs.org/) has a simple search implementation that is more like the swiftype commercial solution. Might be able to port that into pkgdown.

**Comment by pat-s** [comment]
@jayhesselberth Maybe that will even work more reliable than the current implementation? It seems that currently even searching twice does not give a result :(

Would be great if you could get this running :yellow_heart:

**Comment by hadley** [comment]
@jayhesselberth do you want to finish this off or try a different js search lib?

**Comment by jayhesselberth** [comment]
closing in favor of #591

**Pull request closed without merging**
