### PR TITLE
use_appveyor

### PR DESCRIPTION
**Pull request by jayhesselberth**
Test to see if this will trigger an appveyor build.

### CODE REVIEW

**Comment by hadley** [comment]
BTW r-lib is in super weird state on appveyor at the moment. @jennybc knows more than me

**Comment by jennybc** [comment]
> @jennybc knows more than me

Dubious honour, in this case. I just added pkgdown as an AppVeyor project for r-lib and kicked off a build. I had some hope the reports would start to roll in, at the location we all expect. But AppVeyor seems to have fixated on @jimhester's fork of pkgdown from 5 months ago 😑

https://ci.appveyor.com/project/r-lib/pkgdown/build/1.0.1

**Comment by jennybc** [comment]
Aha! I edited project settings to reflect `r-lib/pkgdown`, kicked off a new build, and things look more promising now.

**Comment by jennybc** [comment]
@jayhesselberth Can you make some trivial commit here? My efforts to create a new build only apply to master.

**Comment by jennybc** [comment]
I think you might need to make a fresh PR for AppVeyor to pick up this branch. Or you could just hope for the best, merge, and fiddle further, if need be.

**Comment by jayhesselberth** [comment]
OK will close and re-submit. Does appveyor need to be added under repo Settings > Webhooks? I don't have access, but I see that entry for another repo I have full to and use appveyor on.

**Comment by jimhester** [comment]
I think it is squared away now, when you migrate a repo on GitHub Appveyor doesn't update the project settings, so you have to manually update them to the new location as @jennybc did above.

**Pull request closed without merging**
