### PR TITLE
Test quarto vignette rendering

### LINKED ISSUE #2210: Quarto articles?
I write many "vignettes" that I promptly add to the .Rbuildignore. I don't want to send them to CRAN, but love adding helpful articles to the pkgdown site. Any chance that there will be support for quarto articles (not vignettes)?

### PR DESCRIPTION
**Pull request by jayhesselberth**
Closes #2210

### CODE REVIEW

**Comment by jayhesselberth** [comment]
Would authors need to include `quarto` in `Suggests` for this to work elsewhere?

**Comment by jayhesselberth** [comment]
Hmm, this might be more complicated than I anticipated, the figure links don't work.

**Comment by hadley** [comment]
Yeah, I was going to tackle this soon. Currently pkgdown has a hack to just handle .qmd via rmarkdown, which works for basic vignettes but obviously fails with any quarto specific features. I think getting this to work is a decent amount of work, because we'll need to replicate the template munging code that we currently use for rmarkdown.

**Comment by jayhesselberth** [comment]
That's what I figured. Feel free to close and start fresh.

**Pull request closed without merging**
