### PR TITLE
Support alternate hosts

### LINKED ISSUE #1045: Support GitLab for page source printing
When the `URL` field in the DESCRIPTION file contains github.com, the page source is printed on all reference pages:

```yaml
URL: https://msberends.gitlab.io/AMR, https://github.com/msberends/AMR
```

image

But when the `URL` field contains git**lab**.com, (which it [actually does](https://gitlab.com/msberends/AMR/blob/master/DESCRIPTION)), the page source is not printed:

```yaml
URL: https://msberends.gitlab.io/AMR, https://gitlab.com/msberends/AMR
```
image

The suffix `/blob/master/` also works for GitLab - all full URLs are exactly the same as GitHub, aside from the domain. Any plan to support? Would be great!
And then perhaps also an option in `_pkgdown.yml` to turn this on (default) and off?

### LINKED ISSUE #1238: Support other code hosts
e.g. GitHub enterprise (#676), GitLab (#1045), and sub-directories (#1152)

This requires at least the ability to configure the following URLs:

* A home page, equivalent to (e.g.) `https://github.com/r-lib`, for the navbar.
* A source url, equivalent to (e.g.) `https://github.com/r-lib/pkgdown/blob/master/{path}`, for reference and article source links.
* An issue url, equivalent to (e.g.) `https://github.com/r-lib/issues/{number}`, for NEWS links.
* A person url, equivalent to (e.g.) `https://github.com/{username}`, for NEWS links.

### PR DESCRIPTION
**Pull request by hadley**
Provides new YAML config that allows you to override the defaults (Fixes #1238), and since GitLab and GitHub use the same URL structure, also automatically detects GitLab urs (Fixes #1045).

@msberends would you mind checking that the URLs generate correctly for you?

### CODE REVIEW

**Comment by msberends** [comment]
Thanks, we see (sorry, couldn't resist the CRAN joke 😝, I sometimes get this from one of their maintainers):

```r
pkgdown::build_site(examples = FALSE)
#> Warning message:
#> In path[to_set] <- paste0(path_ext_remove(path[to_set]), ".", rep(ext,  :
#>   number of items to replace is not a multiple of replacement length
```

Relevant (new) YAML part in `./_pkgdown.yml`: 
```yml
repo:
  url:
    home: "https://msberends.gitlab.io/AMR/"
    issues: "https://gitlab.com/msberends/AMR/issues/"
    source: "https://gitlab.com/msberends/AMR/"
``` 

Part in `./DESCRIPTION`:
```
URL: https://msberends.gitlab.io/AMR, https://gitlab.com/msberends/AMR
BugReports: https://gitlab.com/msberends/AMR/issues
```

It did not add an HTML element to the vignettes with the source link, unfortunately (checked the git diff). What kind of debug info would you like?

**Comment by hadley** [comment]
You shouldn't need to do anything to the `_pkgdown.yml`; gitlab detection is automatic. (But I clearly need to improve the documentation because two of the three urls you provided are in the wrong form). Can you please remove that yaml and then run `str(as_pkgdown()$repo)`.

You should be able to see the links from reference/article packages, from the home page, and on the NEWS.

**Comment by jayhesselberth** [comment]
This looks good but I would rely on codecov to ensure it's well tested.

codecov is no longer included in the PR checks. Is (can) codecov run from github actions?

**Comment by hadley** [comment]
@jayhesselberth the test coverage is high; I'll figure out why codecov is no longer running automatically (it should be!).

**Comment by hadley** [comment]
@jayhesselberth it's working again, although I'm not sure what I did fixed it, or whether codecov was having temporary issues.

**Comment by msberends** [comment]
Wow, perhaps not so fast!!

Removed the YAML changes again and as per requested:

```r
str(as_pkgdown()$repo)
#>  NULL
#> Warning message:
#> In path[to_set] <- paste0(path_ext_remove(path[to_set]), ".", rep(ext,  :
#>   number of items to replace is not a multiple of replacement length
```

Also, still no 'Source: <href>' in the vignettes. That's what #1045 was about.

**Comment by msberends** [comment]
Also not the case with the master of 1 sec ago, just tried.

**Comment by hadley** [comment]
If I copy your URL + BugReports into my DESCRIPTION, I get:

```R
> str(as_pkgdown()$repo)
List of 1
 $ url:List of 4
  ..$ home  : chr "https://gitlab.com/msberends/AMR/"
  ..$ source: chr "https://gitlab.com/msberends/AMR/blob/master/"
  ..$ issue : chr "https://gitlab.com/msberends/AMR/issues/"
  ..$ user  : chr "https://gitlab.com/"
```

**Comment by hadley** [comment]
I also fixed that warning message, so I suspect you don't actually have the latest version installed.

**Pull request merged**
