### PR TITLE
Test math rendering in examples

### PR DESCRIPTION
**Pull request by jayhesselberth**
Part of #2704

### CODE REVIEW

**Comment by jayhesselberth** [comment]
@hadley are you ok with setting `math-rendering: mathjax` in the pkgdown site so that this renders correctly? Otherwise will need to figure out why the default `mathml` doesn't work.

**Comment by jayhesselberth** [comment]
@hadley just pinging this, ok to merge? We'll need an test of math rendering in the examples to address #2704 and related issues with math rendering.

**Comment by jayhesselberth** [comment]
I merged this as we're going to need a test of math rendering in the examples. No clear yet why mathml doesn't work in this case.

**Comment by bastistician** [comment]
@jayhesselberth (Just checked the status of the math bug and found this.) Why "in examples"? AFAICS, this test is not about `\examples` but about general Rd math, i.e., how a `\[d]eqn` gets rendered in `/reference/`.
Thanks for working on this!

**Comment by jayhesselberth** [comment]
We didn't have a test in examples, only in a vignette.

**Pull request merged**
