### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by musvaage**
Closes https://github.com/r-lib/pkgdown/issues/2311

NEWS.md
R/build-articles.R
R/build-news.R
R/topics-external.R
tests/testthat/_snaps/build-news.md
tests/testthat/assets/search-site/sitemaps-schema-0.9.xsd
tests/testthat/assets/tutorials/vignettes/tutorials/test-1/test-1.Rmd
tests/testthat/test-highlight.R
tests/testthat/test-navbar.R
tests/testthat/test-rd-example.R
tests/testthat/test-rd-html.R
vignettes/customise.Rmd
vignettes/test/rendering.Rmd

### CODE REVIEW

**Comment by maelle** [comment]
Thank you :slightly_smiling_face: :pray:

**Comment by musvaage** [comment]
@maelle

owing to quotes (roxygen2 Contributor) an approach to the typo `suppoted` in the repo might be reconsidered

```
$ grep -nr suppoted pkgdown
pkgdown/R/build-news.R:154:    warn("Footnotes in NEWS.md are not currently suppoted")
pkgdown/tests/testthat/_snaps/build-news.md:60:      Footnotes in NEWS.md are not currently suppoted
$ 
```

> Snapshots shouldn't be edited by hand - they will change when you run the tests locally after the testing code, or the code that is being tested, changes. At that point you will be prompted to review the snapshot changes, and accept them if the changes you see in the snapshot are expected based on the changes to the code you've made. See the [basic workflow](https://testthat.r-lib.org/articles/snapshotting.html#basic-workflow) section in the Snapshot tests vignette.

and more specific guidelines

> Files in `tests/testthat/_snaps/*.md` are only created and updated by running the tests. They should not be edited by hand - let the running tests update them, review them when prompted with `testthat::snapshot_review()`, then accept the changes with `testthat::snapshot_accept()`

**Comment by musvaage** [comment]
@maelle 

the previous comment has been updated

accordingly, I don't think there are any changes indicated in this pull

**Comment by musvaage** [comment]
@hadley 

I think this can be merged.

**Comment by hadley** [comment]
Thanks!

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
