### PR TITLE
Fix navbar customization logic

### LINKED ISSUE #1569: Breaking change(s) in the new version
* Because it is now possible to not include all elements in the navbar, pkgdown configuration that relied on pkgdown to add unplaced elements (like ggplot2's website configuration) will have an incomplete navbar.

### PR DESCRIPTION
**Pull request by maelle**
Fix #1569

### CODE REVIEW

**Comment by hadley** [comment]
Doesn't this mean that you can no longer remove elements?

**Comment by maelle** [comment]
You can, I have just checked.

image

is the result of

```yaml
navbar:
  structure:
    left:  [intro, reference, articles, tutorials, news]
    right: []
```

**Comment by maelle** [comment]
so I removed the GitHub element.

**Comment by maelle** [comment]
As for ggplot2, this just interverts news and articles in the navbar, but there are no longer missing elements.

**Review by hadley — APPROVED** [review]

**Pull request merged**
